TOKEN_FILE_PATH = '.token'

LOGS_PATH = 'logs/'
LOG_FILENAME_PFX = 'log-'
LOG_FILENAME_EXT = 'csv'

USER_TIMEOUT_SECONDS = 30 * 60

CMD_PREFIX = '/'

CMD_START = 'start'
CMD_MENU = 'menu'
CMD_RULES = 'rules'
CMD_SETTINGS = 'settings'
CMD_PLAY = 'play'
CMD_SURRENDER = 'surrender'
CMD_WHO = 'who'
CMD_TOP = 'top'
CMD_SCORE = 'score'

DIFFICULTY_EASY_TXT = 'лёгкий'
DIFFICULTY_HARD_TXT = 'сложный'

CANDIES_TOTAL_DEFAULT = 150
CANDIES_PER_TURN_DEFAULT = 28
DIFFICUTLY_DEFAULT = DIFFICULTY_HARD_TXT

CALLBACK_NAME_CANDIES_PER_TURN = 'specify_candies_per_turn'
CALLBACK_NAME_CANDIES_TOTAL = 'specify_candies_total'
CALLBACK_NAME_DIFFICULTY = 'specify_difficulty'
CALLBACK_NAME_DIFFICULTY_EASY = CALLBACK_NAME_DIFFICULTY+DIFFICULTY_EASY_TXT
CALLBACK_NAME_DIFFICULTY_HARD = CALLBACK_NAME_DIFFICULTY+DIFFICULTY_HARD_TXT

CALLBACK_NAME_LEAVE_CURRENT = 'leave_current'
CALLBACK_NAME_TO_DEFAULT = 'reset_to_default'

TOP_GAMERS_NUM = 10

MIN_ALLOWED_CANDIES_PER_TURN = 3
MIN_ALLOWED_CANDIES_TOTAL = 5 * MIN_ALLOWED_CANDIES_PER_TURN

MAIN_STICKER_TOKEN = 'CAACAgIAAxkBAAIPlGNya9nVSui_LInSD_5ALeodHiXYAAKvAAPKAwYL781COtWu3kMrBA'
